### PR TITLE
Fix player header icon dark mode colors

### LINKED ISSUE #76: Dark Mode for web
### Description
This will be an iteration on #48. #48 provides an initial dark mode toggle for the electron app. However, since we're [eventually aiming to integrate this locally in the stream-app](https://github.com/peterklingelhofer/stream-app/issues/44) and potentially, if all goes well, host this online, we will need this to be functional for web users as well, so it will work with `yarn start`.

### Potential solution
There's a global state using `useContext` and `useReducer`, check it out in `contexts/globalState.tsx`.

### LINKED ISSUE #89: Background color should change on Dark Mode toggle
Screen Shot 2022-04-25 at 6 12 24 PM
Screen Shot 2022-04-25 at 6 12 34 PM

### Potential Solution
Modify the css file touched by #65

### PR DESCRIPTION
**Pull request by peterklingelhofer**
I've fixed the `Header` icon logo and audio `Player` component's dark mode colors. I've also added a subtle drop shadow to the `Header` and `Player` for some more separation and slight elevation.

Screen Shot 2022-06-23 at 11 22 37 PM

This closes #76.
This closes #89.

Eventually we'll want to implement a toggle for #76 and do this a better way, but this will tide users over for now, and I've created an issue for this: https://github.com/simonv3/beam/issues/163.

### CODE REVIEW

File: src/components/Player.tsx [hunk 1]
```diff
@@ -29,7 +29,15 @@ const playerClass = css`
...
   bottom: 0;
-  background-color: #fff;
+  filter: drop-shadow(0 0 0.075rem #000);
+
+  @media (prefers-color-scheme: dark) {
+    background: #333;
+  }
+
+  @media (prefers-color-scheme: light) {
+    background: #fff;;
```
Comment (simonv3) [inline src/components/Player.tsx:39]: I think this is causing the prettier failure

```suggestion
    background: #fff;
```

File: src/components/AudioWrapper.tsx [hunk 2]
```diff
@@ -167,6 +167,12 @@ export const AudioWrapper: React.FC<{
             box-shadow: none;
             padding: 0;
             margin-right: 1rem;
+            @media (prefers-color-scheme: dark) {
+              filter: invert(80%);
+            }
+            @media (prefers-color-scheme: light) {
+              background: #fff;;
```
Comment (simonv3) [inline src/components/AudioWrapper.tsx:174]:
```suggestion
              background: #fff;
```

**Review by simonv3 — APPROVED** [review]
